version: '3.3'
services:
  pg:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: urban
      POSTGRES_USER: council
      POSTGRES_PASSWORD: abcd
    volumes:
      - ./storage/pg/data:/var/lib/postgresql/data
    ports:
      - 5434:5434
  # clj:
  # ng:
